/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package train;

import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author remir
 */
public class JFrameTrain extends javax.swing.JFrame implements Observateur {

    private static final ImageIcon BLANC = new ImageIcon("./src/imgs/blanc.png");
    private static final ImageIcon MONTAGNE = new ImageIcon("./src/imgs/montagne.png");
    private static final ImageIcon NONCONSTRU = new ImageIcon("./src/imgs/gris.png");
    private static final ImageIcon MONSTRE = new ImageIcon("./src/imgs/monstre.gif");
    private static final ImageIcon VILLE = new ImageIcon("./src/imgs/ville.png");
    private static final ImageIcon TRAIN = new ImageIcon("./src/imgs/train.png");
    private static final ImageIcon RAIL = new ImageIcon("./src/imgs/rail.png");
    
    final int tailleX = 10;
    final int tailleY = 20;
    JLabel[][] jboard;
    
    PlateauModel model;
    
    /**
     * Creates new form JFrameTrain
     */
    public JFrameTrain(PlateauModel _model) {
        model = _model;
        initComponents();
        
        jeuPanel.setLayout(new java.awt.GridLayout(10, 20));
        
        jboard = new JLabel[tailleX][tailleY];
        
        for(int i=0;i<tailleX;i++){
            for(int j=0;j<tailleY;j++){
                // init case
                jboard[i][j] = new JLabel(BLANC);
                jboard[i][j].setIcon(BLANC);
                jeuPanel.add(jboard[i][j]);
                jboard[i][j].addMouseListener(new CaseControler(model, i, j, 0));
            }
        }
    }
    
    void initBoard() {
        updateBoard();
    }
    
    void updateBoard() {
        for(int i=0;i<tailleX;i++){
            for(int j=0;j<tailleY;j++){
                switch (model.board[i][j]) {
                    case 0:
                        jboard[i][j].setIcon(BLANC);
                        break;
                    case 1:
                        jboard[i][j].setIcon(VILLE);
                        break;
                    case 2:
                        jboard[i][j].setIcon(RAIL);
                        break;
                    case 3:
                        jboard[i][j].setIcon(TRAIN);
                        break;
                    case 4:
                        jboard[i][j].setIcon(MONSTRE);
                        break;
                    case 8:
                        jboard[i][j].setIcon(MONTAGNE);
                        break;
                    case 9:
                        jboard[i][j].setIcon(NONCONSTRU);
                        break;
                    default:
                        break;
                }
            }
        }
    }
    
    @Override
    public void avertirNewGame() {
        initBoard();
    }
    
    @Override
    public void avertir() {
        updateBoard();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jeuPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 600));

        jeuPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jeuPanel.setMinimumSize(new java.awt.Dimension(600, 400));

        javax.swing.GroupLayout jeuPanelLayout = new javax.swing.GroupLayout(jeuPanel);
        jeuPanel.setLayout(jeuPanelLayout);
        jeuPanelLayout.setHorizontalGroup(
            jeuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jeuPanelLayout.setVerticalGroup(
            jeuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jeuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jeuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameTrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameTrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameTrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameTrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new JFrameTrain().setVisible(true);
                PlateauModel model = new PlateauModel();
                
                JFrameTrain instance1 = new JFrameTrain(model);
                instance1.setVisible(true);
                model.register(instance1);
                model.nouvellePartie();
                System.out.print(model.toString());
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jeuPanel;
    // End of variables declaration//GEN-END:variables

}
